### ISSUE TITLE
Failed to start neoray due to uninstalled font

### ISSUE THREAD

**Issue by TianYaX** [hismailbulut/Neoray#38] opened 2022-08-11 08:11 UTC
- OS: macOS 13
- Neoray version: v0.2.4
- nvim version: v0.8.0

**Describe the bug:**
When I use a font that is not installed on my system, the following bug occurs.

![image](https://user-images.githubusercontent.com/12004412/184088599-36b88b3f-13bf-4259-b9f7-b26441e66de0.png)

**Comment by hismailbulut** [comment] 2022-08-11 12:08
Thanks TianYaX for both issue and pr. But pr does not fix the issue but hides it. Please try the 7ec4f6c23ba13de924e0cd5d1836783166723abf

**Comment by TianYaX** [comment] 2022-08-11 13:19
I tried to apply this commit(https://github.com/hismailbulut/Neoray/commit/7ec4f6c23ba13de924e0cd5d1836783166723abf) but it doesn't seem to work...

**Comment by TianYaX** [comment] 2022-08-11 13:44
Is it possible to use the default font and give an error? like this pr😄

**Comment by hismailbulut** [comment] 2022-08-11 22:40
> Is it possible to use the default font and give an error? like the pr😄

😂

Actually pr is good but the problem is not using the default font, it's not our fault either.. We must give an error to the user while the Neoray is not launched with nofork and there is only way to do it, show an error message in neovim (actually not only way, we can show a system error dialog). User should know their font is not found by Neoray with this name. Also setting kit to nil is unnecessary here because the kit is already nil and font system will use default font while it is nil. There is no problem with that. Only problem here is neovim does not give a promise us the cursor position will be in the grid area. We can't assert that. The simplest solution is adding a SafeCellAt function to grid and check for bounds and return an empty cell if it out of bounds. Also I liked the system dialog idea (I thought of it while writing this). It will be safer than calling neovim api for showing error message because neovim sometimes does not write this echoerr/msg calls (this is also is not our problem and we can't fix this)
I'm also curious about your opinions

**Comment by TianYaX** [comment] 2022-08-16 02:20
> > Is it possible to use the default font and give an error? like the pr😄
> 
> 😂
> 
> Actually pr is good but the problem is not using the default font, it's not our fault either.. We must give an error to the user while the Neoray is not launched with nofork and there is only way to do it, show an error message in neovim (actually not only way, we can show a system error dialog). User should know their font is not found by Neoray with this name. Also setting kit to nil is unnecessary here because the kit is already nil and font system will use default font while it is nil. There is no problem with that. Only problem here is neovim does not give a promise us the cursor position will be in the grid area. We can't assert that. The simplest solution is adding a SafeCellAt function to grid and check for bounds and return an empty cell if it out of bounds. Also I liked the system dialog idea (I thought of it while writing this). It will be safer than calling neovim api for showing error message because neovim sometimes does not write this echoerr/msg calls (this is also is not our problem and we can't fix this) I'm also curious about your opinions

giving the user an error message is indeed a good interactive experience

**Closed** 2022-08-26 22:01 UTC
